### ISSUE TITLE
API-Doku erstellen

### ISSUE THREAD

**Issue by FabianWilms** [FabianHoltkoetter/WebTech-Backend#18]
Doku für die Frontend-Leute erstellen

**Comment by peter-mueller** [comment]
http://projects.spring.io/spring-restdocs/

Würde das gerne so probieren falls keiner was dagegen hat

**Comment by Falknor** [comment]
Macht euch am Anfang nicht zu viel Aufwand.
Eine simple Beschreibung was wir wohin schicken müssen und was wir bekommen reicht.
