### ISSUE TITLE
Domainmodell erstellen

### ISSUE THREAD

**Issue by FabianWilms** [FabianHoltkoetter/WebTech-Backend#6]
Hier können Vorschläge für das Domain-Modell als Kommentar angefügt werden.

**Comment by FabianWilms** [comment]
![domain](https://docs.google.com/drawings/d/1lu95IIlvC_vYBZsw5VztX_c7M5aR_ThyMZtHFN8EAsI/pub?w=828&amp;h=589)

**Comment by peter-mueller** [comment]
Find ich gut!

Cloze würde ich aufjedenfall nur Test mit Markierungen für Lücken machen, dann spart man sich die Logik das zu trennen.

Mir wäre (glaube) wichtig dass Cloze, Choice und Association nicht Exercise extenden. Sondern Exercise ein Value Object haben, das die speziellen Fragen dann extenden können. Hier les ich aber noch mehr nach wie man das am besten angeht.

**Comment by FabianWilms** [comment]
Zu 1: das sollte das frontend-team entscheiden, für uns ist es egal wie wir es speichern
Zu 2: aber eine Frage ist änderbar und somit ja kein value object

**Comment by toniBianca** [comment]
![web_techniken_architektur_bianca_toni](https://cloud.githubusercontent.com/assets/18287674/14464921/4c58ca9a-00d1-11e6-9c36-2216ae7a0c25.PNG)

**Comment by FabianWilms** [comment]
@toniBianca 
Nur ein paar Sachen die mir auffallen:
- Den `Teacher` und `Student` brauchen wir (eigentlich) nicht, weil das nicht in unserem Scope mit angegeben ist. Für das Gesamtprojekt natürlich richtig, aber das sind auch wieder Sachen die das Frontend-Team nachher irgendwie ansprechen muss und somit mehraufwand für die.
- `Partner` macht, finde ich keinen Sinn
- `Test` macht auch keinen Sinn, wenn würden einem Student das BloomLevel zu einem Themengebiet gespeichert werden. Es gibt ja in dem Sinne keinen "Test", weil man immer weiter Fragen beantworten kann
- Die BloomLevel als enum finde ich gut 👍 
- Ein eigenes `Answer`-Objekt finde ich jetzt eher weniger sinnvoll. Vielleicht sehe ich den Anwendungszweck auch nicht ganz, aber ich weiß auch nicht wie verschachtelt das dann nachher im JSON aussieht.
