### ISSUE TITLE
Exercise und Bloomlevel erstellen

### ISSUE THREAD

**Issue by FabianWilms** [FabianHoltkoetter/WebTech-Backend#8]
Benötigt wird:
- Entität
- Repository
- Such-Methode innerhalb des Repositories um Exercises anhand eines Topics finden zu können

**Comment by FabianWilms** [comment]
#2 #3

**Comment by FabianWilms** [comment]
only merge with #9

**Comment by FabianWilms** [comment]
http://stackoverflow.com/questions/26245351/how-to-query-for-map-values-with-spring-data-jpa

**Comment by peter-mueller** [comment]
Noch nicht richtig, topicBloomLevel ist ein VO, deswegen wird auch das Topic noch nicht referenziert

**Comment by FabianWilms** [comment]
mMn. einfach anstatt `Topic topic` `long topicID` verwenden.

**Comment by toniBianca** [comment]
Wurde das jetzt nicht bereits in MR #11 und #13 umgesetzt?
